version: '3'

services:
  client:
    build: ./client
    container_name: spotty-client
    ports:
      - '8080:8080'
    volumes:
      - ./client:/usr/spotty/client
    environment:
      - SPOTTY_API_URL=http://localhost:3000
      - SPOTTY_BASE_URL=http://localhost:8080
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: spotty-mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    environment:
      MONGO_INITDB_DATABASE: spotty
      MONGO_INITDB_ROOT_USERNAME: spotty
      MONGO_INITDB_ROOT_PASSWORD: spotty

