/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SpottyPlayback {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLSpottyPlaybackElement extends Components.SpottyPlayback, HTMLStencilElement {}
  var HTMLSpottyPlaybackElement: {
    prototype: HTMLSpottyPlaybackElement;
    new (): HTMLSpottyPlaybackElement;
  };
  interface HTMLElementTagNameMap {
    'spotty-playback': HTMLSpottyPlaybackElement;
  }
}

declare namespace LocalJSX {
  interface SpottyPlayback {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'spotty-playback': SpottyPlayback;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'spotty-playback': LocalJSX.SpottyPlayback & JSXBase.HTMLAttributes<HTMLSpottyPlaybackElement>;
    }
  }
}


